id: P004312
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W3CN3374
  title: འབྲུ་འགྲེལ་འཕྲུལ་ལྡེའི་གསལ་འགྲེལ།
  author: ''
  volumes:
    3071632c41794ca5af576c113ae9bfb5:
      image_group_id: I3CN3527
      title: ''
      volume_number: 1
      total_pages: 226
      base_file: v001.txt
